# Generated by Django 4.1.7 on 2023-05-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInputs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banknoteImage", models.ImageField(upload_to="userInput")),
            ],
        ),
    ]
