# Generated by Django 4.1.7 on 2023-05-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Frontend", "0002_userinputs"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserInputs",
            new_name="UserInput",
        ),
    ]
